version: "3.9"

services:
  nginx:
    build: ./
    ports:
      - 127.0.0.1:9090:80
    environment:
      - CROWDSEC_API_URL=http://crowdsec:8080
      - CROWDSEC_API_KEY=1234
  crowdsec:
    image: crowdsecurity/crowdsec:v1.5.0-rc2
    environment:
      - BOUNCER_KEY_NGINX=1234
